from app.schemas.investigation import InvestigationTask
from app.services.model_adapter import ModelAdapter


class ReferenceModelAdapter(ModelAdapter):
    """
    Reference implementation for integrating a real
    remote-sensing ML model into SatQuery AI.

    This class is intentionally model-agnostic.

    The ML developer can copy this class and replace
    the predict() logic with their actual model inference.
    """

    def predict(
        self,
        task: InvestigationTask,
        image_paths: list[str],
        execution_context: dict | None = None,
    ) -> dict:
        """
        Run model inference for an investigation task.

        Parameters
        ----------
        task:
            Investigation task selected by the Mission Agent.

        image_paths:
            Paths to the input GeoTIFF files.

        execution_context:
            Results from upstream investigation tasks,
            if this task depends on another specialist.

        Returns
        -------
        dict
            Standard model output containing:
            - result
            - confidence
            - evidence
        """

        # ---------------------------------------------
        # 1. Validate inputs
        # ---------------------------------------------

        if not image_paths:
            raise ValueError(
                "At least one image is required."
            )

        # ---------------------------------------------
        # 2. Access upstream results
        # ---------------------------------------------

        previous_results = {}

        if execution_context:

            previous_results = (
                execution_context.get(
                    "previous_results",
                    {}
                )
            )

        # ---------------------------------------------
        # 3. TODO: Load your real ML model
        # ---------------------------------------------

        # Example:
        #
        # model = load_your_model()
        #
        # prediction = model.predict(
        #     image_paths=image_paths,
        #     query=task.query,
        #     context=previous_results
        # )

        # ---------------------------------------------
        # 4. Temporary reference output
        # ---------------------------------------------

        return {
            "answer": (
                "Reference adapter executed successfully."
            ),

            "task_type": task.task_type,

            "image_count": len(
                image_paths
            ),

            "upstream_task_count": len(
                previous_results
            ),

            "confidence": 0.0,

            "evidence": [
                {
                    "type": "visual",
                    "description": (
                        "Reference adapter output. "
                        "Replace this with evidence "
                        "generated by the real model."
                    )
                }
            ]
        }